#!/bin/bash
# MAINTAINER Aario <Aario@luexu.com>
set -e

. /etc/aa/entrypointbase

Timezone=${Timezone:-""}
Host=${Host:-"nginxdocker"}
LogTag=${LogTag:-"nginxent[$$]"}
GenSslCrt=${GenSslCrt:-""}

aaLog() {
    AaLog --aalogheader_host "${Host}" --aalogtag "${LogTag}" "$@"
}

AaAdjustTime "${Timezone}"
GenSslCrt "${GenSslCrt}"

RunningSignal ${RunningID:-''}

# You have to run nginx server with root privilege
exec "$@"
